=== hmrc/organisations-details-api/resources/public/api/conf/1.0/schemas/corporation-tax-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Pay As You Earn",
  "type": "object",
  "properties": {
    "taxSolvencyStatus": {
      "type": "string",
      "description": "The tax solvency status for the organisation. A - Administrative Order, V - Voluntary Arrangement, S - Solvent, I - Insolvent.",
      "enum": [
        "A",
        "V",
        "S",
        "I"
      ]
    },
    "_links": {
      "type": "object",
      "description": "A list of links for possible actions related to this endpoint.",
      "properties": {
        "self": {
          "type": "object",
          "description": "The URI for this endpoint."
        }
      }
    },
    "dateOfRegistration": {
      "type": "string",
      "description": "The registration date for the company.",
      "id": "full-date",
      "example": "2018-04-06"
    },
    "accountingPeriods": {
      "type": "array",
      "description": "The accounting periods.",
      "items": {
        "type": "object",
        "properties": {
          "accountingPeriodStartDate": {
            "type": "string",
            "description": "The start date of the accounting period.",
            "id": "full-date",
            "example": "2018-04-06"
          },
          "accountingPeriodEndDate": {
            "type": "string",
            "description": "The end date of the accounting period.",
            "id": "full-date",
            "example": "2018-10-05"
          },
          "turnover": {
            "type": "number",
            "description": "The amount of money taken by an organisation in the accounting period. Turnover is recorded in thousands of pounds (rounded to the nearest Â£1,000). Turnover is in the range of -1 to 99999999999.",
            "example": "2340"
          }
        },
        "required": [
          "accountingPeriodStartDate",
          "accountingPeriodEndDate",
          "turnover"
        ]
      }
    }
  },
  "required": [
    "dateOfRegistration",
    "taxSolvencyStatus",
    "accountingPeriods"
  ]
}

=== hmrc/organisations-details-api/resources/public/api/conf/1.0/examples/corporation-tax-response.json
{
  "_links": {
    "self": {
      "href": "/organisations/details/corporation-tax?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430"
    }
  },
  "taxSolvencyStatus": "V",
  "dateOfRegistration": "2015-04-21",
  "accountingPeriods": [
    {
      "accountingPeriodStartDate": "2018-04-06",
      "accountingPeriodEndDate": "2018-10-05",
      "turnover": 38390
    },
    {
      "accountingPeriodStartDate": "2018-10-06",
      "accountingPeriodEndDate": "2019-04-05",
      "turnover": 2340
    }
  ]
}
